version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: chimera_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
      # Mount the host's /etc/letsencrypt directory read-only
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - frontend
      - backend
    networks:
      - chimera_network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: chimera_frontend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://chimerastack.com
    networks:
      - chimera_network
    restart: always
    volumes:
      - frontend-build:/app/build

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: chimera_backend
    volumes:
      - ./backend/src:/var/www/html
      - ./backend/logs:/var/log
      - ./backend/downloads:/var/www/html/downloads
    environment:
      - PHP_ENVIRONMENT=production
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
      - JWT_SECRET=${JWT_SECRET}
      - PHP_DEBUG=true
    depends_on:
      - mysql
    networks:
      - chimera_network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: chimera_mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - chimera_network
    restart: always

networks:
  chimera_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  frontend-build:
    driver: local
