project:
  environment: development
  framework: react-php
  language: fullstack
  name: chimera-web-platform
services:
  backend:
    build:
      context: ./backend
    environment:
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
    - 8000:80
  frontend:
    build:
      context: ./frontend
    environment:
      REACT_APP_API_URL: http://localhost:8000
    ports:
    - 3000:3000
  mysql:
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
    - 3300:3306
  phpmyadmin:
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_USER: ${MYSQL_USER}
    ports:
    - 8081:80
